// Icons are sourced from lucide-react and re-exported with Icon* aliases
// for backwards compatibility with existing consumers.
export {
  Activity        as IconActivity,
  ArrowRight      as IconArrowRight,
  Bell            as IconBell,
  Calendar        as IconCalendar,
  Check           as IconCheck,
  CircleCheck     as IconCheckCircle,
  ChevronDown     as IconChevronDown,
  ChevronLeft     as IconChevronLeft,
  ChevronRight    as IconChevronRight,
  Clock           as IconClock,
  X               as IconClose,
  LayoutDashboard as IconDashboard,
  Droplet         as IconDroplet,
  Dumbbell        as IconDumbbell,
  Pencil          as IconEdit,
  Flame           as IconFlame,
  Heart           as IconHeart,
  Menu            as IconMenu,
  Dumbbell        as IconMuscle,
  Plus            as IconPlus,
  Footprints      as IconRun,
  Search          as IconSearch,
  Settings        as IconSettings,
  Star            as IconStar,
  Target          as IconTarget,
  Trash2          as IconTrash,
  TrendingUp      as IconTrendUp,
  Trophy          as IconTrophy,
  User            as IconUser,
  Weight          as IconWeight,
  Zap             as IconZap,
} from 'lucide-react'
